trigger:
- master
- azure-pipelines

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

name: $(BuildID)-$(Build.SourceBranchName)

variables:
  ${{ if notIn(variables['Build.SourceBranchName'], 'master', 'azure-pipelines') }}:
    buildImage: false
    deployService: false
    deployEnvironment: 'no'
    imageTags: 'no'
    serviceName: 'no'
  ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.SourceBranchName'], 'azure-pipelines')) }}:
    buildImage: true
    deployService: true
    deployEnvironment: production
    imageTags: |
      $(Build.BuildId)
      latest
    serviceName: salary_front

stages:
- stage: PackInDocker
  displayName: Build docker image
  condition: and(succeeded(), ${{variables.buildImage}})
  jobs:
  - job: Public
    steps:
      - task: Docker@2
        displayName: Build image for docker hub
        inputs:
          containerRegistry: 'rtuitlab connection by admin'
          repository: 'rtuitlab/salary-front'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: ${{variables.imageTags}}
  - job: Private
    steps:
      - task: Docker@2
        displayName: Build image for private docker registry
        inputs:
          containerRegistry: 'private rtuitlab registry'
          repository: 'salary/salary-front'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: ${{variables.imageTags}}
- stage: UpdateService
  displayName: Update service
  condition: and(succeeded(), ${{variables.deployService}})
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{variables.deployEnvironment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image registry.rtuitlab.dev/salary/salary-front:$(Build.BuildId) ${{variables.serviceName}} --with-registry-auth'
                readyTimeout: '20000'
